### ISSUE TITLE
Hangs on "Waiting for another flutter command to release the startup lock..."

### ISSUE THREAD

**Issue by avi-mastov** [bitrise-steplib/bitrise-step-flutter-test#12]
Build Log:
[10ff142778be88f9.log](https://github.com/bitrise-steplib/bitrise-step-flutter-test/files/5506048/10ff142778be88f9.log)

This happens ever since I added some dozens of unit tests. The step doesn't start running the tests and fails.

The step configuration:
```yaml
      - flutter-test@0.10:
          inputs:
            - additional_params: test
```

When run locally with bitrise cli, it succeeds.

**Comment by non-binary** [comment]
Hi @avi-mastov,

Please add a Script step between the two steps with the content `killall -9 dart`.

**Comment by avi-mastov** [comment]
Thanks @non-binary.

It actually stopped happening after I edited the tests again. If it happens again, I'll add the killall script.

**Comment by avi-mastov** [comment]
Hi, I'm reopening the issue because it started happening again. The script step didn't help, because it failed:
[5ac0dfe5969a60b6.log](https://github.com/bitrise-steplib/bitrise-step-flutter-test/files/5693988/5ac0dfe5969a60b6.log). No process was found.

Workflow yml:
```yml
  sanity-check:
    steps:
    - activate-ssh-key@4.0.5:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0: {}
    - flutter-installer@0:
        inputs:
        - version: "$FLUTTER_VERSION"
    - script@1:
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # debug log
            set -x

            # write your script here
            flutter packages pub global activate intl_utils
            flutter pub global run intl_utils:generate

            # or run a script from your repository, like:
            # bash ./path/to/script.sh
            # not just bash, e.g.:
            # ruby ./path/to/script.rb
    - flutter-analyze@0.3:
        inputs:
        - project_location: "$BITRISE_FLUTTER_PROJECT_LOCATION"
    - script@1:
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # debug log
            set -x

            # workaround for flutter getting stuck between steps
            killall -9 dart

            # or run a script from your repository, like:
            # bash ./path/to/script.sh
            # not just bash, e.g.:
            # ruby ./path/to/script.rb
    - flutter-test@0.10:
        inputs:
        - additional_params: test
    - deploy-to-bitrise-io@1:
        inputs:
        - deploy_path: "$BITRISE_TEST_RESULT_DIR"
```
