### ISSUE TITLE
Does not support globs

### ISSUE THREAD

**Issue by maxlapides** [bitrise-steplib/bitrise-step-flutter-test#3]
Consider this configuration:

```yaml
- flutter-test@0.9.1:
        inputs:
        - additional_params: "lib/**/*_test.dart"
```

In this case, it will run

```bash
flutter "test" "lib/**/*_test.dart" 
```

Because the glob pattern is wrapped in quotes, the glob will not be expanded.
